#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/library
#  jpa:
#    show-ddl: true
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8090


spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 51cf5e063f4c9cb8242e
            clientSecret: 480634afdca05ae8caf3a16860c3c701040fe983
logging:
  level:
    root: debug